# Overlays for the Odroid platform

dtbo-$(CONFIG_ARCH_ROCKCHIP_ODROIDM1) += \
	i2c0.dtbo \
	i2c1.dtbo \
	onewire.dtbo \
	pwm1.dtbo \
	pwm2.dtbo \
	pwm9.dtbo \
	spi0.dtbo \
	uart0-with-ctsrts.dtbo \
	uart0.dtbo \
	uart1.dtbo

targets += $(dtbo-y)
always := $(dtbo-y)
