# Overlays for the Odroid platform

dtbo-$(CONFIG_ARCH_ROCKCHIP_ODROIDM1) += \
	blueled_off.dtbo \
	board_stepper.dtbo \
	dht11.dtbo \
	display_3_5.dtbo \
	display_5_0.dtbo \
	display_vu8s.dtbo \
	fiq0_to_uart2.dtbo \
	hktft32.dtbo \
	i2c0.dtbo \
	i2c1.dtbo \
	mcp2515.dtbo \
	mcp2515_12mhz.dtbo \
	mcp2515_16mhz.dtbo \
	onewire.dtbo \
	ov5647.dtbo \
	pcf8563.dtbo \
	pwm1.dtbo \
	pwm2.dtbo \
	pwm3.dtbo \
	rknpu.dtbo \
	spi0.dtbo \
	ttyfiq0_115200.dtbo \
	uart0-with-ctsrts.dtbo \
	uart0.dtbo \
	uart1.dtbo

targets += $(dtbo-y)
always := $(dtbo-y)
